/**
 * Storylets parametrizados: arquetipos + familias del vertical slice.
 * Los eventos legacy del pack se adaptan en situationDirector.
 */
import type { SituationArchetype } from './types';

export const SITUATION_ARCHETYPES: SituationArchetype[] = [
  // —— Roster conflicts ——
  {
    id: 'roster_rift',
    family: 'roster',
    titleTemplate: 'Fisura en el roster',
    bodyTemplate:
      '{{actor}} te corta el paso en {{venue}}. La causa: {{cause}}. {{other}} mira desde atrás sin meterse… todavía.',
    stages: ['academy', 'challengers', 'tier1', 'worlds'],
    actors: ['coach', 'duo'],
    venues: ['academy', 'cafe', 'arena'],
    causes: ['derrota fea', 'tardanza al scrim', 'ego en voice', 'rotación de titular'],
    activityTags: ['scrim', 'match', 'vod'],
    weight: 11,
    cooldownTurns: 12,
    actorCooldownTurns: 8,
    threadKind: 'roster_rift',
    choices: [
      {
        id: 'mediate',
        label: 'Mediar en el medio',
        verb: 'talk',
        hint: 'Acercate y bajá la tensión',
        effect: { stats: { teamwork: 5, mentality: 2 }, relations: { coach: 3, duo: 3 } },
        outcome: 'Bajaste la temperatura. Quedó anotado.',
      },
      {
        id: 'back_actor',
        label: 'Respaldar a {{actor}}',
        verb: 'talk',
        effect: { stats: { teamwork: 2 } },
        actorRelations: { primary: 5, others: -4 },
        outcome: 'Tomaste partido. El otro no lo olvida.',
      },
      {
        id: 'confront',
        label: 'Confrontar de frente',
        verb: 'timing',
        hint: 'Timing de voz firme',
        effect: { stats: { mentality: 4, reputation: 2 }, relations: { coach: -2, duo: -2 } },
        outcome: 'Quedó claro quién manda el tono.',
      },
      {
        id: 'walk_away',
        label: 'Retirarte de la zona',
        verb: 'talk',
        effect: { stats: { mentality: -3 }, relations: { coach: -1, duo: -1 } },
        outcome: 'Te fuiste. El conflicto sigue vivo.',
      },
    ],
  },
  {
    id: 'sub_pressure',
    family: 'roster',
    titleTemplate: 'Amenaza de suplente',
    bodyTemplate:
      '{{actor}} te muestra el celular: el staff habla de rotar. Motivo: {{cause}}. Estás en {{venue}}.',
    stages: ['challengers', 'tier1', 'worlds'],
    actors: ['coach', 'manager'],
    venues: ['academy', 'arena', 'cafe'],
    causes: ['forma baja', 'fatiga visible', 'mala serie', 'presión del board'],
    requireRelations: { coach: 20 },
    weight: 9,
    cooldownTurns: 14,
    actorCooldownTurns: 10,
    threadKind: 'starting_spot',
    choices: [
      {
        id: 'prove',
        label: 'Pedir lab extra',
        verb: 'timing',
        effect: { stats: { mechanics: 5, mentality: 3 }, relations: { coach: 4 } },
        outcome: 'Compraste tiempo con sangre.',
      },
      {
        id: 'negotiate_role',
        label: 'Negociar el rol',
        verb: 'sort',
        hint: 'Ordená prioridades en el papel',
        effect: { stats: { teamwork: 4, money: -2 }, relations: { manager: 3, coach: 2 } },
        outcome: 'Reordenaste expectativas.',
      },
      {
        id: 'ignore_noise',
        label: 'Ignorar el ruido',
        verb: 'talk',
        effect: { stats: { mentality: -4, reputation: 2 }, relations: { coach: -3 } },
        outcome: 'El rumor crece sin respuesta.',
      },
    ],
  },
  {
    id: 'duo_trust_test',
    family: 'roster',
    titleTemplate: 'Test de confianza',
    bodyTemplate:
      '{{actor}} se cruzó de brazos. "{{cause}}". El lugar: {{venue}}. Quiere una respuesta, no un speech.',
    stages: ['soloq', 'academy', 'challengers', 'tier1'],
    actors: ['duo'],
    venues: ['home', 'cafe', 'academy'],
    causes: ['promesa rota de duo', 'clip incómodo', 'llamada en ranked', 'silencio post-derrota'],
    activityTags: ['soloq', 'content', 'rest'],
    weight: 10,
    cooldownTurns: 10,
    actorCooldownTurns: 7,
    threadKind: 'roster_rift',
    choices: [
      {
        id: 'apologize',
        label: 'Reconocer el error',
        verb: 'talk',
        effect: { stats: { mentality: 3, teamwork: 4 }, relations: { duo: 7 } },
        outcome: 'Se distiende. Anotan la página.',
      },
      {
        id: 'explain',
        label: 'Explicar el contexto',
        verb: 'sort',
        effect: { stats: { gameSense: 3 }, relations: { duo: 2 } },
        outcome: 'Entiende… a medias.',
      },
      {
        id: 'deflect',
        label: 'Cambiar de tema',
        verb: 'talk',
        effect: { stats: { mentality: -2 }, relations: { duo: -5 } },
        outcome: 'Queda un filo entre ustedes.',
      },
    ],
  },

  // —— Sponsor / contract ——
  {
    id: 'sponsor_offer',
    family: 'sponsor',
    titleTemplate: 'Oferta sobre la mesa',
    bodyTemplate:
      '{{actor}} abre una carpeta en {{venue}}. Cláusula clave: {{cause}}. Podés inspeccionar, negociar o firmar a ciegas.',
    stages: ['academy', 'challengers', 'tier1', 'worlds'],
    actors: ['manager'],
    venues: ['cafe', 'home', 'academy'],
    causes: ['exclusividad de stream', 'apariencia en redes', 'bonus por wins', 'penalidad por tilt público'],
    activityTags: ['content'],
    weight: 10,
    cooldownTurns: 12,
    actorCooldownTurns: 9,
    threadKind: 'sponsor',
    minigame: {
      kind: 'negotiation',
      title: 'Mesa de contrato',
      blurb: 'Leé la letra chica bajo presión.',
      difficulty: 2,
    },
    choices: [
      {
        id: 'inspect',
        label: 'Inspeccionar cláusulas',
        verb: 'sort',
        hint: 'Arrastrá y ordená los papeles',
        effect: { stats: { money: 3, reputation: 2 }, relations: { manager: 2 } },
        outcome: 'Encontraste una trampa. Mejor posición.',
      },
      {
        id: 'negotiate',
        label: 'Negociar el %',
        verb: 'timing',
        effect: { stats: { money: 6, reputation: 1 }, relations: { manager: 4 } },
        outcome: 'Sacaste un punto más. Firmás con sonrisa tensa.',
      },
      {
        id: 'sign_fast',
        label: 'Firmar ya',
        verb: 'talk',
        effect: { stats: { money: 8, mentality: -2 }, relations: { manager: 5, coach: -2 } },
        outcome: 'Plata rápida. El team mira de reojo.',
      },
      {
        id: 'walk_deal',
        label: 'Rechazar la mesa',
        verb: 'talk',
        effect: { stats: { reputation: 3, money: -1 }, relations: { manager: -4 } },
        outcome: 'Quedás limpio… y más pobre.',
      },
    ],
  },
  {
    id: 'contract_renewal',
    family: 'sponsor',
    titleTemplate: 'Renovación en juego',
    bodyTemplate:
      '{{actor}} pone el reloj sobre la mesa en {{venue}}. El board aprieta por {{cause}}.',
    stages: ['challengers', 'tier1', 'worlds'],
    actors: ['manager', 'coach'],
    venues: ['cafe', 'academy'],
    causes: ['números flojos', 'edad en el radar', 'otra oferta rival', 'cláusula de salida'],
    weight: 9,
    cooldownTurns: 16,
    actorCooldownTurns: 12,
    threadKind: 'contract',
    choices: [
      {
        id: 'ask_raise',
        label: 'Pedir suba',
        verb: 'timing',
        effect: { stats: { money: 7, mentality: 2 }, relations: { manager: -2, coach: 1 } },
        outcome: 'Forcejeaste el número.',
      },
      {
        id: 'security',
        label: 'Priorizar seguridad',
        verb: 'sort',
        effect: { stats: { money: 3, mentality: 5 }, relations: { manager: 4, coach: 3 } },
        outcome: 'Menos upside, más piso.',
      },
      {
        id: 'threaten_leave',
        label: 'Amenazar con irte',
        verb: 'talk',
        effect: { stats: { reputation: 4, teamwork: -4 }, relations: { manager: -5, coach: -3 } },
        outcome: 'Quedó el puente medio quemado.',
      },
    ],
  },

  // —— Performance / health ——
  {
    id: 'performance_dip',
    family: 'performance',
    titleTemplate: 'Señal roja',
    bodyTemplate:
      'En {{venue}} ves las señales: {{cause}}. {{actor}} ya lo notó. Hay que diagnosticar antes de que explote.',
    stages: ['soloq', 'academy', 'challengers', 'tier1', 'worlds'],
    actors: ['coach', 'duo', 'manager'],
    venues: ['home', 'gym', 'academy'],
    causes: ['muñeca cargada', 'sueño roto', 'tilt silencioso', 'setup fallando', 'ansiedad pre-serie'],
    activityTags: ['soloq', 'rest', 'match'],
    weight: 11,
    cooldownTurns: 11,
    actorCooldownTurns: 8,
    threadKind: 'burnout',
    choices: [
      {
        id: 'physio',
        label: 'Tratamiento / fisio',
        verb: 'timing',
        effect: { stats: { mentality: 5, mechanics: 2 }, relations: { coach: 2 } },
        outcome: 'Bajás carga. El cuerpo agradece.',
      },
      {
        id: 'train_through',
        label: 'Empujar el grind',
        verb: 'timing',
        effect: { stats: { mechanics: 6, mentality: -5 }, relations: { coach: 1, duo: -1 } },
        outcome: 'Rendís hoy; pagás mañana.',
      },
      {
        id: 'full_rest',
        label: 'Protocolo de descanso',
        verb: 'talk',
        effect: { stats: { mentality: 7, mechanics: -2 }, relations: { duo: 2 } },
        outcome: 'Apagás el PC. La forma espera.',
      },
      {
        id: 'fix_setup',
        label: 'Arreglar el setup',
        verb: 'sort',
        effect: { stats: { mechanics: 4, money: -3 }, relations: { manager: 1 } },
        outcome: 'Cableado limpio. Menos fricción.',
      },
    ],
  },
  {
    id: 'voice_chaos',
    family: 'roster',
    titleTemplate: 'Caos en voice',
    bodyTemplate:
      'En {{venue}}, {{actor}} corta a todos. Motivo: {{cause}}. {{other}} se queda callado un segundo de más.',
    stages: ['academy', 'challengers', 'tier1'],
    actors: ['coach', 'duo'],
    venues: ['academy', 'cafe'],
    causes: ['call contradictorio', 'ping spam', 'tilt post-fight', 'horario corrido'],
    activityTags: ['scrim', 'vod'],
    weight: 9,
    cooldownTurns: 11,
    actorCooldownTurns: 7,
    threadKind: 'roster_rift',
    choices: [
      {
        id: 'reset_comms',
        label: 'Resetear comms',
        verb: 'talk',
        effect: { stats: { teamwork: 6, mentality: 2 }, relations: { coach: 3, duo: 3 } },
        outcome: 'Volvieron a hablar en el mismo idioma.',
      },
      {
        id: 'side_actor',
        label: 'Bancarle el call a {{actor}}',
        verb: 'talk',
        actorRelations: { primary: 5, others: -3 },
        effect: { stats: { teamwork: 1 } },
        outcome: 'Quedó un bando. El otro lo marca.',
      },
      {
        id: 'mute_self',
        label: 'Mute propio y focus',
        verb: 'timing',
        effect: { stats: { mechanics: 4, teamwork: -3 }, relations: { coach: -2 } },
        outcome: 'Jugaste limpio, pero el team quedó frío.',
      },
    ],
  },
  {
    id: 'starting_spot_leak',
    family: 'roster',
    titleTemplate: 'Filtración de titular',
    bodyTemplate:
      '{{actor}} te muestra un pantallazo en {{venue}}: el board discute tu spot por {{cause}}.',
    stages: ['challengers', 'tier1', 'worlds'],
    actors: ['manager', 'coach'],
    venues: ['academy', 'arena', 'cafe'],
    causes: ['serie chata', 'contenido > lab', 'comparativa con academy', 'fatiga pública'],
    weight: 10,
    cooldownTurns: 16,
    actorCooldownTurns: 10,
    threadKind: 'starting_spot',
    choices: [
      {
        id: 'own_it',
        label: 'Pedir feedback duro',
        verb: 'talk',
        effect: { stats: { mentality: 3, gameSense: 4 }, relations: { coach: 4 } },
        outcome: 'Dolor útil. Quedó plan.',
      },
      {
        id: 'pr_spin',
        label: 'Armar narrativa con {{manager}}',
        verb: 'sort',
        effect: { stats: { reputation: 5, money: -2 }, relations: { manager: 4, coach: -1 } },
        outcome: 'El ruido se vuelve controlado.',
      },
      {
        id: 'shadow_queue',
        label: 'Grind secreto',
        verb: 'timing',
        effect: { stats: { mechanics: 6, mentality: -2 }, relations: { duo: 2 } },
        outcome: 'Subís nivel en silencio.',
      },
    ],
  },
  {
    id: 'brand_ambush',
    family: 'sponsor',
    titleTemplate: 'Emboscada de marca',
    bodyTemplate:
      '{{actor}} te espera en {{venue}} con un brief express: {{cause}}. Hay cámara cerca.',
    stages: ['academy', 'challengers', 'tier1', 'worlds'],
    actors: ['manager'],
    venues: ['cafe', 'arena', 'home'],
    causes: ['drop de merch', 'clip viral', 'rival con el mismo sponsor', 'deadline de campaña'],
    activityTags: ['content'],
    weight: 9,
    cooldownTurns: 12,
    actorCooldownTurns: 8,
    threadKind: 'sponsor',
    choices: [
      {
        id: 'take_brief',
        label: 'Aceptar el brief',
        verb: 'sort',
        effect: { stats: { reputation: 5, money: 6, mentality: -2 }, relations: { manager: 4 } },
        outcome: 'Plata rápida. Agenda más densa.',
      },
      {
        id: 'protect_focus',
        label: 'Proteger el focus competitivo',
        verb: 'talk',
        effect: { stats: { mentality: 3, reputation: -2 }, relations: { manager: -3, coach: 3 } },
        outcome: '{{coach}} asiente. {{manager}} anota la fricción.',
      },
      {
        id: 'renegotiate',
        label: 'Renegociar alcance',
        verb: 'timing',
        effect: { stats: { money: 3, reputation: 2 }, relations: { manager: 2 } },
        outcome: 'Quedó un alcance más sano.',
      },
    ],
  },
  {
    id: 'clause_trap',
    family: 'sponsor',
    titleTemplate: 'Cláusula escondida',
    bodyTemplate:
      'En {{venue}}, {{actor}} señala una línea del PDF: {{cause}}. {{other}} ya firmó algo parecido.',
    stages: ['challengers', 'tier1', 'worlds'],
    actors: ['manager', 'coach'],
    venues: ['cafe', 'academy'],
    causes: ['exclusividad de stream', 'penalidad por no clasificar', 'imagen con rival', 'NDA de draft'],
    weight: 8,
    cooldownTurns: 14,
    actorCooldownTurns: 9,
    threadKind: 'contract',
    choices: [
      {
        id: 'lawyer_up',
        label: 'Pedir revisión legal',
        verb: 'sort',
        effect: { stats: { money: -4, mentality: 2 }, relations: { manager: 1, coach: 2 } },
        outcome: 'Más lento, más seguro.',
      },
      {
        id: 'sign_anyway',
        label: 'Firmar y seguir',
        verb: 'talk',
        effect: { stats: { money: 8, reputation: 3 }, relations: { manager: 5 }, flags: { riskyClause: 1 } },
        outcome: 'Plata ahora. Riesgo después.',
      },
      {
        id: 'walk_paper',
        label: 'Levantarte de la mesa',
        verb: 'talk',
        effect: { stats: { reputation: 2, money: -2 }, relations: { manager: -4 } },
        outcome: 'Quedó claro tu límite.',
      },
    ],
  },
  {
    id: 'late_night_spiral',
    family: 'performance',
    titleTemplate: 'Espiral de madrugada',
    bodyTemplate:
      'Son las 3 en {{venue}}. {{actor}} te mira la cara: {{cause}}. El setup sigue prendido.',
    stages: ['soloq', 'academy', 'challengers', 'tier1'],
    actors: ['duo', 'coach'],
    venues: ['home', 'gym', 'cafe'],
    causes: ['LP tilt', 'insomnio', 'caffeine crash', 'doomscroll de reddit'],
    activityTags: ['soloq', 'rest'],
    weight: 10,
    cooldownTurns: 10,
    actorCooldownTurns: 6,
    threadKind: 'burnout',
    choices: [
      {
        id: 'force_sleep',
        label: 'Apagar todo',
        verb: 'talk',
        effect: { stats: { mentality: 6, mechanics: -2 }, relations: { duo: 3 } },
        outcome: 'Dormís. Mañana existe.',
      },
      {
        id: 'one_more',
        label: 'Una más',
        verb: 'timing',
        effect: { stats: { mechanics: 3, mentality: -5 }, relations: { coach: -2 } },
        outcome: 'Una más… y otra.',
      },
      {
        id: 'walk_block',
        label: 'Salir a caminar',
        verb: 'sort',
        effect: { stats: { mentality: 4, teamwork: 1 }, relations: { duo: 2 } },
        outcome: 'El aire corta el loop.',
      },
    ],
  },
  {
    id: 'form_check',
    family: 'performance',
    titleTemplate: 'Chequeo de forma',
    bodyTemplate:
      '{{actor}} te para en {{venue}}. Ve un problema concreto: {{cause}}. ¿Cómo lo encarás?',
    stages: ['academy', 'challengers', 'tier1', 'worlds'],
    actors: ['coach', 'manager'],
    venues: ['academy', 'arena'],
    causes: ['farm flojo', 'muertes tempranas', 'poca presencia en mapa', 'composiciones predecibles'],
    activityTags: ['vod', 'scrim', 'match'],
    weight: 9,
    cooldownTurns: 11,
    actorCooldownTurns: 7,
    choices: [
      {
        id: 'accept_plan',
        label: 'Aceptar plan de lab',
        verb: 'sort',
        effect: { stats: { gameSense: 5, mentality: 2 }, relations: { coach: 5 } },
        outcome: 'Plan concreto. Menos ego.',
      },
      {
        id: 'argue_sample',
        label: 'Discutir la muestra',
        verb: 'talk',
        effect: { stats: { mentality: -2, reputation: 1 }, relations: { coach: -3 } },
        outcome: 'Defendiste el sample. Quedó roce.',
      },
      {
        id: 'prove_queue',
        label: 'Probarlo en cola',
        verb: 'timing',
        effect: { stats: { mechanics: 5, mentality: 1 }, relations: { coach: 2, duo: 2 } },
        outcome: 'Los números hablan después.',
      },
    ],
  },
  {
    id: 'rival_probe',
    family: 'performance',
    titleTemplate: 'El rival te mide',
    bodyTemplate:
      '{{actor}} aparece en {{venue}} con una sonrisa de scout. Empuja el tema: {{cause}}.',
    stages: ['soloq', 'academy', 'challengers', 'tier1', 'worlds'],
    actors: ['rival'],
    venues: ['cafe', 'arena', 'gym'],
    causes: [
      'tu último highlight',
      'rumor de suplente',
      'comparación de puntuación',
      'plan de equipo filtrado',
    ],
    weight: 8,
    cooldownTurns: 10,
    actorCooldownTurns: 6,
    threadKind: 'rivalry',
    choices: [
      {
        id: 'banter',
        label: 'Banter limpio',
        verb: 'talk',
        effect: { stats: { reputation: 3, mentality: 2 }, relations: { rival: 4 } },
        outcome: 'Queda respeto. Y material de clip.',
      },
      {
        id: 'ice',
        label: 'Cortar en seco',
        verb: 'talk',
        effect: { stats: { mentality: 1 }, relations: { rival: -3 } },
        outcome: 'Silencio incómodo. Victoria chica.',
      },
      {
        id: 'challenge',
        label: 'Desafiar a customs',
        verb: 'timing',
        effect: { stats: { mechanics: 4, reputation: 2 }, relations: { rival: 6 } },
        outcome: 'Customs pactados. Cuando el heat suba, viene el cara a cara.',
      },
    ],
  },
  {
    id: 'rival_customs',
    family: 'performance',
    titleTemplate: 'Customs bajo fuego',
    bodyTemplate:
      '{{actor}} te espera en {{venue}}. Ya no es chiste: quiere customs por {{cause}}. La rivalidad escala.',
    stages: ['academy', 'challengers', 'tier1', 'worlds'],
    actors: ['rival'],
    venues: ['cafe', 'arena', 'gym'],
    causes: ['tu última serie', 'un clip viral', 'un scout en voice', 'el draft filtrado'],
    weight: 11,
    cooldownTurns: 9,
    actorCooldownTurns: 5,
    threadKind: 'rivalry',
    choices: [
      {
        id: 'accept_customs',
        label: 'Aceptar customs',
        verb: 'timing',
        effect: { stats: { mechanics: 5, mentality: 1, reputation: 2 }, relations: { rival: 5 } },
        outcome: 'Customs densos. El hilo arde — falta el showdown en arena.',
      },
      {
        id: 'public_refuse',
        label: 'Rechazar en público',
        verb: 'talk',
        effect: { stats: { mentality: 2, reputation: -1 }, relations: { rival: -4 } },
        outcome: 'Quedó frío. El circuit habla igual.',
      },
      {
        id: 'coach_mediate',
        label: 'Meter al coach de mediador',
        verb: 'sort',
        effect: { stats: { teamwork: 3 }, relations: { rival: 2, coach: 3 } },
        outcome: 'Marek baja la temperatura. Un poco.',
      },
    ],
  },
  {
    id: 'rival_showdown',
    family: 'performance',
    titleTemplate: 'Cara a cara',
    bodyTemplate:
      '{{actor}} te corta el paso en {{venue}}. Trash talk por {{cause}}. La próxima serie es personal.',
    stages: ['academy', 'challengers', 'tier1', 'worlds'],
    actors: ['rival'],
    venues: ['arena', 'cafe', 'gym'],
    causes: ['la serie de esta semana', 'un leak de starting', 'tu maestría', 'el público'],
    weight: 13,
    cooldownTurns: 8,
    actorCooldownTurns: 4,
    threadKind: 'rivalry',
    choices: [
      {
        id: 'stare_down',
        label: 'Aguantar la mirada',
        verb: 'timing',
        effect: { stats: { mentality: 4, reputation: 3 }, relations: { rival: 3 } },
        outcome: 'No parpadeás. La próxima serie es contra él.',
      },
      {
        id: 'clap_back',
        label: 'Responder al trash',
        verb: 'timing',
        effect: { stats: { reputation: 4, mentality: -1 }, relations: { rival: 6 } },
        outcome: 'Clip. Guerra declarada. Próxima serie: showdown.',
      },
      {
        id: 'walk_away',
        label: 'Darle la espalda',
        verb: 'talk',
        effect: { stats: { mentality: 2 }, relations: { rival: -5, coach: 2 } },
        outcome: 'Te vas. Marek asiente. El showdown queda en pausa.',
      },
    ],
  },
  {
    id: 'rival_aftermath_win',
    family: 'performance',
    titleTemplate: 'La deuda se paga',
    bodyTemplate:
      'Después del showdown, {{actor}} te encuentra en {{venue}}. Por {{cause}}, el tono cambió: ya no es trash — es respeto a regañadientes.',
    stages: ['academy', 'challengers', 'tier1', 'worlds'],
    actors: ['rival'],
    venues: ['arena', 'cafe', 'gym', 'home'],
    causes: ['el scoreboard', 'el clip del teamfight', 'la serie completa', 'el público'],
    weight: 0,
    cooldownTurns: 99,
    actorCooldownTurns: 99,
    threadKind: 'rivalry',
    choices: [
      {
        id: 'respect_nod',
        label: 'Aceptar el respeto',
        verb: 'talk',
        effect: { stats: { reputation: 4, mentality: 3 }, relations: { rival: 4, coach: 2 } },
        outcome: 'Un apretón seco. La rivalidad sigue, pero el rango quedó claro.',
      },
      {
        id: 'keep_fire',
        label: 'Dejar la puerta abierta a la revancha',
        verb: 'talk',
        effect: { stats: { reputation: 3, mentality: 2 }, relations: { rival: 6 } },
        outcome: 'Sonreís. "Cuando quieras." El circuit ya tiene título para el rematch.',
      },
      {
        id: 'lock_in',
        label: 'Volver al laburo con el coach',
        verb: 'sort',
        effect: { stats: { gameSense: 3, teamwork: 2 }, relations: { coach: 4, rival: 1 } },
        outcome: 'Marek corta la celebración. Hay split por cerrar.',
      },
    ],
  },
  {
    id: 'rival_aftermath_loss',
    family: 'performance',
    titleTemplate: 'La cuenta pendiente',
    bodyTemplate:
      '{{actor}} no celebra en tu cara — peor: te espera en {{venue}} con calma. Habla de {{cause}}. La deuda quedó escrita.',
    stages: ['academy', 'challengers', 'tier1', 'worlds'],
    actors: ['rival'],
    venues: ['arena', 'cafe', 'gym', 'home'],
    causes: ['tu draft', 'el late game', 'un error de macro', 'la presión del split'],
    weight: 0,
    cooldownTurns: 99,
    actorCooldownTurns: 99,
    threadKind: 'rivalry',
    choices: [
      {
        id: 'own_it',
        label: 'Bancártela en voz alta',
        verb: 'talk',
        effect: { stats: { mentality: 4, reputation: 2 }, relations: { rival: 3, coach: 2 } },
        outcome: 'Admittís el gap. El rival asiente. Dolor útil.',
      },
      {
        id: 'vod_hunt',
        label: 'Pedir VOD y cazar el error',
        verb: 'sort',
        effect: { stats: { gameSense: 5, mentality: 1 }, relations: { coach: 3, rival: 2 } },
        outcome: 'Marek abre la grabación. La revancha empieza en el pause.',
      },
      {
        id: 'cold_silence',
        label: 'Guardar silencio y apuntar',
        verb: 'timing',
        effect: { stats: { mentality: 2, mechanics: 2 }, relations: { rival: -2 } },
        outcome: 'No das material de clip. Por dentro, el fire quedó prendido.',
      },
    ],
  },

  // —— Sedes con identidad propia (una sola venue) ——
  {
    id: 'gym_spotter',
    family: 'performance',
    titleTemplate: 'Spotter inesperado',
    bodyTemplate:
      '{{actor}} aparece en {{venue}} mientras cargás. Habla de {{cause}} entre series. El gym no es neutral.',
    stages: ['soloq', 'academy', 'challengers', 'tier1', 'worlds'],
    actors: ['rival'],
    venues: ['gym'],
    causes: ['tu forma física', 'el split', 'un rumor de suplente', 'customs'],
    weight: 10,
    cooldownTurns: 9,
    actorCooldownTurns: 5,
    threadKind: 'rivalry',
    choices: [
      {
        id: 'spot_ok',
        label: 'Dejarlo spottear',
        verb: 'timing',
        effect: { stats: { mechanics: 2, mentality: 2 }, relations: { rival: 4 }, form: 2 },
        outcome: 'Rep limpia. Respeto de vestuario.',
      },
      {
        id: 'spot_ego',
        label: 'Subir el peso por ego',
        verb: 'timing',
        effect: { stats: { reputation: 2, mentality: -2 }, relations: { rival: 3 }, fatigue: 5 },
        outcome: 'El clip mental queda. La espalda protesta.',
      },
      {
        id: 'spot_leave',
        label: 'Cambiar de máquina',
        verb: 'talk',
        effect: { stats: { mentality: 1 }, relations: { rival: -2 } },
        outcome: 'Te vas. Guerra fría entre racks.',
      },
    ],
  },
  {
    id: 'gym_physio_flags',
    family: 'performance',
    titleTemplate: 'La fisio te frena',
    bodyTemplate:
      'En {{venue}} te marcan {{cause}}. {{actor}} ya se enteró — o se va a enterar.',
    stages: ['academy', 'challengers', 'tier1', 'worlds'],
    actors: ['coach', 'manager'],
    venues: ['gym'],
    causes: ['dolor de muñeca', 'sueño roto', 'carga de semana', 'un tirón viejo'],
    weight: 9,
    cooldownTurns: 11,
    actorCooldownTurns: 6,
    choices: [
      {
        id: 'physio_rest',
        label: 'Bajar la carga',
        verb: 'choice',
        effect: {
          stats: { mentality: 3 },
          form: 2,
          fatigue: -8,
          relations: { coach: 3 },
        },
        outcome: 'Priorizás el cuerpo. El staff respira.',
      },
      {
        id: 'physio_push',
        label: 'Igual al scrim',
        verb: 'timing',
        effect: {
          stats: { reputation: 2, mentality: -1 },
          fatigue: 6,
          relations: { coach: -2, manager: 1 },
        },
        outcome: 'Te bancás. Queda anotado “arriesga”.',
      },
      {
        id: 'physio_hide',
        label: 'No decir nada',
        verb: 'talk',
        effect: { stats: { mentality: -2 }, relations: { coach: -1 }, fatigue: 3 },
        outcome: 'Silencio. El dolor no firma NDAs.',
      },
    ],
  },
  {
    id: 'academy_whiteboard',
    family: 'roster',
    titleTemplate: 'Pizarra en disputa',
    bodyTemplate:
      '{{actor}} borra tu plan en {{venue}}. Quiere cambiar por {{cause}}. {{other}} mira el marcador.',
    stages: ['academy', 'challengers', 'tier1', 'worlds'],
    actors: ['coach', 'duo'],
    venues: ['academy'],
    causes: ['el draft de ayer', 'un call fallido', 'scout del rival', 'ego de lane'],
    activityTags: ['scrim', 'vod'],
    weight: 11,
    cooldownTurns: 9,
    actorCooldownTurns: 5,
    threadKind: 'roster_rift',
    choices: [
      {
        id: 'board_listen',
        label: 'Escuchar el plan nuevo',
        verb: 'sort',
        effect: { stats: { gameSense: 4, teamwork: 3 }, relations: { coach: 4, duo: 2 } },
        outcome: 'Borron y cuenta nueva. Menos ego.',
      },
      {
        id: 'board_defend',
        label: 'Defender tu trazo',
        verb: 'talk',
        effect: { stats: { mentality: 2, reputation: 1 }, relations: { coach: -2, duo: 1 } },
        outcome: 'Quedó roce. También quedó tu idea.',
      },
      {
        id: 'board_hybrid',
        label: 'Híbrido de ambos',
        verb: 'timing',
        effect: { stats: { teamwork: 4, gameSense: 2 }, relations: { coach: 2, duo: 3 } },
        outcome: 'Un plan que nadie odia. Sirve.',
      },
    ],
  },
  {
    id: 'academy_late_scrim',
    family: 'performance',
    titleTemplate: 'Llegás tarde al scrim',
    bodyTemplate:
      '{{actor}} te espera en {{venue}} con el timer en rojo. La excusa de hoy: {{cause}}.',
    stages: ['academy', 'challengers', 'tier1', 'worlds'],
    actors: ['coach'],
    venues: ['academy'],
    causes: ['el café', 'el gym', 'una cola ranked', 'el tránsito'],
    activityTags: ['scrim'],
    weight: 10,
    cooldownTurns: 10,
    actorCooldownTurns: 6,
    choices: [
      {
        id: 'late_own',
        label: 'Ownarlo y entrar',
        verb: 'timing',
        effect: { stats: { mentality: 2, teamwork: 2 }, relations: { coach: 3 }, fatigue: 2 },
        outcome: 'Sin drama. Marek respeta la honestidad.',
      },
      {
        id: 'late_excuse',
        label: 'Excusa elaborada',
        verb: 'talk',
        effect: { stats: { reputation: -1 }, relations: { coach: -3, duo: -1 } },
        outcome: 'Nadie compra. Peor que llegar tarde.',
      },
      {
        id: 'late_extra',
        label: 'Ofrecer VOD extra',
        verb: 'timing',
        effect: { stats: { gameSense: 3, teamwork: 2 }, relations: { coach: 4 }, fatigue: 4 },
        outcome: 'Pagás con lab. El roster sigue.',
      },
    ],
  },
  {
    id: 'home_doomscroll',
    family: 'performance',
    titleTemplate: 'Doomscroll a las 2am',
    bodyTemplate:
      'En {{venue}} la pantalla no se apaga. El tema del feed: {{cause}}. {{actor}} manda un “¿seguís up?”.',
    stages: ['soloq', 'academy', 'challengers', 'tier1', 'worlds'],
    actors: ['duo'],
    venues: ['home'],
    causes: ['un clip tuyo', 'un hate thread', 'el rival trending', 'rumor de roster'],
    weight: 9,
    cooldownTurns: 10,
    actorCooldownTurns: 6,
    threadKind: 'burnout',
    choices: [
      {
        id: 'scroll_sleep',
        label: 'Apagar y dormir',
        verb: 'choice',
        effect: { stats: { mentality: 4 }, fatigue: -10, form: 2, relations: { duo: 2 } },
        outcome: 'Luces off. Mañana existe.',
      },
      {
        id: 'scroll_reply',
        label: 'Responder al hate',
        verb: 'timing',
        effect: { stats: { reputation: 2, mentality: -3 }, fatigue: 4, relations: { manager: -1 } },
        outcome: 'Quote tweet. El manager ya está despierto.',
      },
      {
        id: 'scroll_duo',
        label: 'Queue con el dúo',
        verb: 'timing',
        effect: { stats: { mechanics: 3, teamwork: 2 }, fatigue: 5, relations: { duo: 4 } },
        outcome: 'Una ranked a las 2. Amistad > sueño.',
      },
    ],
  },
  {
    id: 'home_clip_leak',
    family: 'sponsor',
    titleTemplate: 'Clip que no debía salir',
    bodyTemplate:
      '{{actor}} llama a {{venue}}: un clip de {{cause}} está dando vueltas. Hay que decidir ya.',
    stages: ['academy', 'challengers', 'tier1', 'worlds'],
    actors: ['manager'],
    venues: ['home'],
    causes: ['voice tilt', 'un chiste de vestuario', 'draft spoilers', 'queja al staff'],
    weight: 10,
    cooldownTurns: 12,
    actorCooldownTurns: 7,
    choices: [
      {
        id: 'leak_own',
        label: 'Ownarlo en público',
        verb: 'talk',
        effect: { stats: { reputation: 3, mentality: 2 }, relations: { manager: 3 } },
        outcome: 'Controlás la narrativa. Duele menos.',
      },
      {
        id: 'leak_kill',
        label: 'Pedir takedown',
        verb: 'sort',
        effect: { stats: { reputation: -1, money: -2 }, relations: { manager: 4, coach: 1 } },
        outcome: 'Legal se mueve. El circuit igual vio algo.',
      },
      {
        id: 'leak_ignore',
        label: 'Ignorar y laburar',
        verb: 'timing',
        effect: { stats: { mechanics: 3, mentality: 1 }, relations: { manager: -2, coach: 2 } },
        outcome: 'Mute al ruido. Marek asiente.',
      },
    ],
  },
  {
    id: 'cafe_table_scout',
    family: 'sponsor',
    titleTemplate: 'Scout en la mesa de al lado',
    bodyTemplate:
      'En {{venue}}, {{actor}} te baja la voz: hay un scout escuchando {{cause}}. {{other}} ya lo miró de reojo.',
    stages: ['academy', 'challengers', 'tier1', 'worlds'],
    actors: ['manager', 'rival'],
    venues: ['cafe'],
    causes: ['tu última serie', 'un tryout filtrado', 'tu maestría de rol', 'el rumor de suplente'],
    weight: 11,
    cooldownTurns: 10,
    actorCooldownTurns: 6,
    choices: [
      {
        id: 'scout_perform',
        label: 'Hablar como pro',
        verb: 'talk',
        effect: { stats: { reputation: 4, mentality: 1 }, relations: { manager: 3 } },
        outcome: 'El scout anota. Sola sonríe sin abrir el deal todavía.',
      },
      {
        id: 'scout_humble',
        label: 'Bajar el ego',
        verb: 'choice',
        effect: { stats: { mentality: 3, teamwork: 2 }, relations: { manager: 2, coach: 2 } },
        outcome: 'Cero show. Quedás como serio. El rival odia el silencio.',
      },
      {
        id: 'scout_flex',
        label: 'Flexear el highlight',
        verb: 'timing',
        effect: { stats: { reputation: 3, mentality: -2 }, relations: { rival: 3, manager: 1 } },
        outcome: 'Clip mental. El scout se ríe. Marek va a enterarse.',
      },
    ],
  },
  {
    id: 'cafe_group_chat',
    family: 'roster',
    titleTemplate: 'El group chat explota',
    bodyTemplate:
      '{{actor}} te muestra el celular en {{venue}}. El chat del circuit vira por {{cause}}. {{other}} ya está tipeando.',
    stages: ['soloq', 'academy', 'challengers', 'tier1', 'worlds'],
    actors: ['duo', 'manager'],
    venues: ['cafe'],
    causes: ['un leak de starting', 'un clapback tuyo', 'un meme del rival', 'plata de scrim'],
    weight: 10,
    cooldownTurns: 9,
    actorCooldownTurns: 5,
    choices: [
      {
        id: 'chat_mute',
        label: 'Mute y café',
        verb: 'choice',
        effect: { stats: { mentality: 4 }, relations: { duo: 2, manager: -1 } },
        outcome: 'Salís del hilo. El drama sigue sin vos.',
      },
      {
        id: 'chat_mediate',
        label: 'Bajar la temperatura',
        verb: 'talk',
        effect: { stats: { teamwork: 4, reputation: 2 }, relations: { duo: 3, manager: 2 } },
        outcome: 'Mensaje corto. El chat se calma un rato.',
      },
      {
        id: 'chat_quote',
        label: 'Meter un quote limpio',
        verb: 'timing',
        effect: { stats: { reputation: 3, mentality: -1 }, relations: { manager: 3, rival: 2 } },
        outcome: 'Una línea. El circuit la usa de sticker.',
      },
    ],
  },
  {
    id: 'arena_draft_lock',
    family: 'performance',
    titleTemplate: 'Lock-in del draft',
    bodyTemplate:
      '{{actor}} te para en {{venue}} con el clipboard. Hay que cerrar el pick por {{cause}}. El timer no perdona.',
    stages: ['challengers', 'tier1', 'worlds'],
    actors: ['coach'],
    venues: ['arena'],
    causes: ['un ban sorpresa', 'tu ego de lane', 'el plan del VOD', 'el miedo al rival'],
    activityTags: ['match'],
    weight: 12,
    cooldownTurns: 8,
    actorCooldownTurns: 4,
    choices: [
      {
        id: 'draft_follow',
        label: 'Seguir el plan',
        verb: 'sort',
        effect: { stats: { gameSense: 4, teamwork: 3 }, relations: { coach: 5 }, form: 2 },
        outcome: 'Lock limpio. Marek asiente una vez.',
      },
      {
        id: 'draft_flex',
        label: 'Pedir el flex raro',
        verb: 'timing',
        effect: { stats: { mechanics: 3, reputation: 2, mentality: -1 }, relations: { coach: -2 } },
        outcome: 'Pick ego. El staff anota “discutir después”.',
      },
      {
        id: 'draft_safe',
        label: 'Ir a lo seguro',
        verb: 'choice',
        effect: { stats: { mentality: 2, teamwork: 2 }, relations: { coach: 3 }, form: 1 },
        outcome: 'Cero poesía. Entrás al mapa entero.',
      },
    ],
  },
  {
    id: 'arena_crowd_noise',
    family: 'performance',
    titleTemplate: 'El público no calla',
    bodyTemplate:
      'En {{venue}} las cámaras ya apuntan. {{actor}} menciona {{cause}}. {{other}} ajusta el headset sin mirarte.',
    stages: ['challengers', 'tier1', 'worlds'],
    actors: ['rival', 'coach'],
    venues: ['arena'],
    causes: ['tu último tilt', 'un chant del rival', 'la serie de esta noche', 'un rumor de roster'],
    activityTags: ['match'],
    weight: 11,
    cooldownTurns: 9,
    actorCooldownTurns: 5,
    threadKind: 'rivalry',
    choices: [
      {
        id: 'crowd_focus',
        label: 'Auriculares full',
        verb: 'timing',
        effect: { stats: { mentality: 4, mechanics: 2 }, form: 2 },
        outcome: 'Mute al mundo. Solo queda el draft.',
      },
      {
        id: 'crowd_feed',
        label: 'Usar la energía',
        verb: 'talk',
        effect: { stats: { reputation: 3, mentality: 1 }, relations: { rival: 3 }, fatigue: 2 },
        outcome: 'El ruido suma. El rival lo nota.',
      },
      {
        id: 'crowd_coach',
        label: 'Pedir el huddle',
        verb: 'choice',
        effect: { stats: { teamwork: 3 }, relations: { coach: 4, rival: -1 } },
        outcome: 'Marek te saca del foco. Prioridad clara.',
      },
    ],
  },
  {
    id: 'arena_bench_heat',
    family: 'roster',
    titleTemplate: 'El banco calienta',
    bodyTemplate:
      '{{actor}} te para en el túnel de {{venue}}. El suplente está listo por {{cause}}. {{other}} ya tiene el speech.',
    stages: ['challengers', 'tier1', 'worlds'],
    actors: ['coach', 'manager'],
    venues: ['arena'],
    causes: ['tu fatiga', 'un VOD flojo', 'presión del board', 'la racha del rival'],
    weight: 10,
    cooldownTurns: 11,
    actorCooldownTurns: 6,
    threadKind: 'starting_spot',
    choices: [
      {
        id: 'bench_own',
        label: 'Ownarlo y pedir minutos',
        verb: 'talk',
        effect: { stats: { mentality: 3, reputation: 2 }, relations: { coach: 3 }, form: 2 },
        outcome: 'Sin drama. Quedás como starter con trabajo.',
      },
      {
        id: 'bench_prove',
        label: 'Probarlo en el warm-up',
        verb: 'timing',
        effect: { stats: { mechanics: 4, teamwork: 1 }, relations: { coach: 2 }, fatigue: 3 },
        outcome: 'Manos calientes. El suplente espera.',
      },
      {
        id: 'bench_accept',
        label: 'Aceptar rotación corta',
        verb: 'choice',
        effect: {
          stats: { teamwork: 3, mentality: -1 },
          relations: { coach: 2, manager: 3 },
          fatigue: -4,
        },
        outcome: 'Cedés un mapa. El staff guarda el favor.',
      },
    ],
  },
  {
    id: 'home_setup_fail',
    family: 'performance',
    titleTemplate: 'El setup te traiciona',
    bodyTemplate:
      'En {{venue}} muere {{cause}}. {{actor}} manda un “¿seguís up?”. La ranked no espera.',
    stages: ['soloq', 'academy', 'challengers', 'tier1', 'worlds'],
    actors: ['duo'],
    venues: ['home'],
    causes: ['el mouse', 'el headset', 'el router', 'un driver raro'],
    weight: 10,
    cooldownTurns: 10,
    actorCooldownTurns: 5,
    choices: [
      {
        id: 'setup_fix',
        label: 'Arreglarlo ya',
        verb: 'sort',
        effect: { stats: { mentality: 2, gameSense: 1 }, fatigue: 3, relations: { duo: 2 } },
        outcome: 'Cable nuevo, drama viejo. Entrás tarde pero entero.',
      },
      {
        id: 'setup_duo',
        label: 'Ir a la booth del dúo',
        verb: 'talk',
        effect: { stats: { teamwork: 3, mechanics: 2 }, relations: { duo: 5 }, fatigue: 2 },
        outcome: 'Jugás en su setup. Química salva la noche.',
      },
      {
        id: 'setup_tilt',
        label: 'Forzar con lo que hay',
        verb: 'timing',
        effect: { stats: { mechanics: 2, mentality: -3 }, form: -2, fatigue: 4 },
        outcome: 'Jugás mal. El dúo lo nota en el primer fight.',
      },
    ],
  },
  {
    id: 'gym_recovery_week',
    family: 'performance',
    titleTemplate: 'Semana de recovery',
    bodyTemplate:
      '{{actor}} te corta en {{venue}}: esta semana es recovery por {{cause}}. El ego pide otra cosa.',
    stages: ['academy', 'challengers', 'tier1', 'worlds'],
    actors: ['coach'],
    venues: ['gym'],
    causes: ['tu fatiga alta', 'un tirón viejo', 'el board mirando forma', 'demasiadas series'],
    weight: 9,
    cooldownTurns: 12,
    actorCooldownTurns: 7,
    choices: [
      {
        id: 'rec_obey',
        label: 'Obedecer el plan',
        verb: 'choice',
        effect: {
          stats: { mentality: 3 },
          form: 4,
          fatigue: -12,
          relations: { coach: 5 },
        },
        outcome: 'Pesas livianas. Llegás entero al fin de semana.',
      },
      {
        id: 'rec_half',
        label: 'Mitad gym, mitad SoloQ',
        verb: 'timing',
        effect: {
          stats: { mechanics: 2, mentality: 1 },
          form: 1,
          fatigue: -4,
          relations: { coach: 1 },
        },
        outcome: 'Compromiso. Marek no aplaude, tampoco castiga.',
      },
      {
        id: 'rec_ignore',
        label: 'Ignorar y full grind',
        verb: 'talk',
        effect: {
          stats: { mechanics: 3, reputation: 1, mentality: -2 },
          fatigue: 8,
          form: -2,
          relations: { coach: -4 },
        },
        outcome: 'Ego gana hoy. El cuerpo cobra mañana.',
      },
    ],
  },
  {
    id: 'academy_bootcamp_curfew',
    family: 'roster',
    titleTemplate: 'Toque de queda',
    bodyTemplate:
      '{{actor}} clava la regla en {{venue}}: curfew por {{cause}}. {{other}} mira el reloj del scrim.',
    stages: ['academy', 'challengers', 'tier1', 'worlds'],
    actors: ['coach', 'duo'],
    venues: ['academy'],
    causes: ['scrims nocturnos', 'fatiga del roster', 'un leak de VOD', 'el split apretado'],
    activityTags: ['scrim', 'vod'],
    weight: 10,
    cooldownTurns: 10,
    actorCooldownTurns: 5,
    choices: [
      {
        id: 'curfew_respect',
        label: 'Respetar el curfew',
        verb: 'choice',
        effect: {
          stats: { teamwork: 3, mentality: 2 },
          fatigue: -6,
          form: 2,
          relations: { coach: 4, duo: 2 },
        },
        outcome: 'Luces off. El roster llega entero mañana.',
      },
      {
        id: 'curfew_one',
        label: 'Una ranked y a dormir',
        verb: 'timing',
        effect: {
          stats: { mechanics: 2 },
          fatigue: 2,
          relations: { coach: -1, duo: 3 },
        },
        outcome: 'Una. El dúo jura que fue la última.',
      },
      {
        id: 'curfew_push',
        label: 'Pedir scrim extra',
        verb: 'talk',
        effect: {
          stats: { teamwork: 2, reputation: 2, mentality: -1 },
          fatigue: 7,
          relations: { coach: 2, duo: -2 },
        },
        outcome: 'Marek acepta a regañadientes. Alguien odia la idea.',
      },
    ],
  },

  // —— Arco de temporada (solo force; no sale en la ruleta) ——
  {
    id: 'mid_season_checkin',
    family: 'performance',
    titleTemplate: 'Mitad de split',
    bodyTemplate:
      '{{actor}} te para en {{venue}}. “Vamos a mitad de camino.” El tema: {{cause}}. Lo que elijas marca el resto del split.',
    stages: ['soloq', 'academy', 'challengers', 'tier1', 'worlds'],
    actors: ['coach', 'manager'],
    causes: [
      'números del split',
      'forma vs fatiga',
      'presión del board',
      'comparación con el rival',
    ],
    weight: 0,
    cooldownTurns: 99,
    actorCooldownTurns: 99,
    choices: [
      {
        id: 'double_load',
        label: 'Doblar la carga',
        verb: 'timing',
        hint: 'Timing de compromiso',
        effect: {
          stats: { mechanics: 4, reputation: 3, mentality: -2 },
          form: 3,
          fatigue: 8,
          relations: { coach: 4 },
        },
        outcome: 'Más lab. El cuerpo protesta; el staff aplaude.',
      },
      {
        id: 'protect_form',
        label: 'Cuidar la forma',
        verb: 'choice',
        effect: {
          stats: { mentality: 5 },
          form: 4,
          fatigue: -6,
          relations: { coach: 2, manager: -1 },
        },
        outcome: 'Menos ego. Llegás entero al tramo final.',
      },
      {
        id: 'ask_bonus',
        label: 'Pedir un adelanto',
        verb: 'talk',
        effect: {
          stats: { money: 5, reputation: 1 },
          relations: { manager: 3, coach: -1 },
        },
        outcome: 'Plata ahora. El coach anota “prioridad plata”.',
      },
    ],
  },

  // —— Identidad de rol (solo dispara si jugás ese carril) ——
  {
    id: 'mid_roam_blame',
    family: 'roster',
    titleTemplate: 'Saliste de mid y te culpan',
    bodyTemplate:
      '{{actor}} te corta en {{venue}}: te fuiste a ayudar y dejaste tu línea sola. Motivo: {{cause}}. {{other}} no dice nada, pero se nota.',
    stages: ['academy', 'challengers', 'tier1'],
    roleTags: ['mid'],
    actors: ['coach', 'duo'],
    venues: ['home', 'academy', 'cafe'],
    causes: [
      'ayuda que no cerró',
      'perdiste presión en mid',
      'el rival llegó con teletransporte',
      'oleada que se te vino encima',
    ],
    activityTags: ['soloq', 'scrim', 'match'],
    weight: 14,
    cooldownTurns: 10,
    actorCooldownTurns: 7,
    threadKind: 'roster_rift',
    choices: [
      {
        id: 'own_it',
        label: 'Bancarte el error',
        verb: 'talk',
        effect: { stats: { mentality: 3, gameSense: 3 }, relations: { coach: 4, duo: 2 } },
        outcome: 'Responsabilidad. La review duele menos.',
      },
      {
        id: 'explain_tempo',
        label: 'Explicar por qué saliste',
        verb: 'talk',
        effect: { stats: { gameSense: 5 }, relations: { coach: -1, duo: 1 } },
        outcome: 'Defendiste la lectura. Quedó roce.',
      },
      {
        id: 'lab_roams',
        label: 'Practicar salidas en customs',
        verb: 'timing',
        effect: { stats: { mechanics: 4, gameSense: 2 }, relations: { coach: 3 } },
        outcome: 'Compraste perdón con reps.',
      },
    ],
  },
  {
    id: 'mid_prio_vs_side',
    family: 'performance',
    titleTemplate: '¿Presionar mid o ir a ayudar?',
    bodyTemplate:
      'Decisión rápida en {{venue}}: ¿seguís empujando mid o rotás a otra línea? {{actor}} empuja {{cause}}. Si fallás el call, se nota en el marcador.',
    stages: ['challengers', 'tier1', 'worlds'],
    roleTags: ['mid'],
    actors: ['coach', 'duo'],
    venues: ['academy', 'arena'],
    causes: [
      'objetivo chico por pelear',
      'estado de la oleada',
      'poca visión en el río',
      'teletransporte rival listo',
    ],
    activityTags: ['scrim', 'match', 'vod'],
    weight: 13,
    cooldownTurns: 11,
    actorCooldownTurns: 7,
    choices: [
      {
        id: 'hold_prio',
        label: 'Seguir presionando mid',
        verb: 'choice',
        effect: { stats: { gameSense: 4, mechanics: 2 }, relations: { coach: 2 } },
        outcome: 'Controlaste la oleada. El mapa respiró.',
      },
      {
        id: 'rotate_side',
        label: 'Ir a ayudar la otra línea',
        verb: 'timing',
        effect: { stats: { teamwork: 5, gameSense: 2 }, relations: { duo: 4, coach: 1 } },
        outcome: 'Llegaste a tiempo. El lado agradece.',
      },
      {
        id: 'defer_call',
        label: 'Dejar la decisión al coach',
        verb: 'talk',
        effect: { stats: { mentality: -2 }, relations: { coach: 3 } },
        outcome: 'Menos ego. Menos ownership.',
      },
    ],
  },
  {
    id: 'jgl_path_leak',
    family: 'performance',
    titleTemplate: 'Te leyeron la ruta',
    bodyTemplate:
      '{{actor}} marca tu recorrido en {{venue}}. Empuja {{cause}}. En voice piden cambiar el plan… o invadir igual.',
    stages: ['academy', 'challengers', 'tier1', 'worlds'],
    roleTags: ['jungle'],
    actors: ['coach', 'rival'],
    venues: ['home', 'academy', 'arena'],
    causes: [
      'visión enemiga profunda',
      'clip del rival',
      'patrón demasiado predecible',
      'te trackean los campamentos',
    ],
    activityTags: ['vod', 'scrim', 'match'],
    weight: 14,
    cooldownTurns: 10,
    actorCooldownTurns: 6,
    threadKind: 'rivalry',
    choices: [
      {
        id: 'change_path',
        label: 'Cambiar la ruta ya',
        verb: 'sort',
        effect: { stats: { gameSense: 6 }, relations: { coach: 4 } },
        outcome: 'Nuevo recorrido. El rival pierde el rastro.',
      },
      {
        id: 'invade_anyway',
        label: 'Invadir igual',
        verb: 'timing',
        effect: { stats: { mechanics: 4, mentality: 2 }, relations: { rival: 3, coach: -2 } },
        outcome: 'Jugada de ego. Si sale, highlight; si no, review.',
      },
      {
        id: 'ward_lab',
        label: 'Lab de visión primero',
        verb: 'talk',
        effect: { stats: { gameSense: 4, teamwork: 2 }, relations: { coach: 3, duo: 2 } },
        outcome: 'Visión primero. Ruta después.',
      },
    ],
  },
  {
    id: 'jgl_steal_call',
    family: 'performance',
    titleTemplate: '¿Robar el objetivo o soltar?',
    bodyTemplate:
      'Objetivo grande en {{venue}}. {{actor}} grita el call: {{cause}}. El golpe final está en tus manos.',
    stages: ['tier1', 'worlds'],
    roleTags: ['jungle'],
    actors: ['coach'],
    venues: ['arena', 'academy'],
    causes: [
      'setup de Baron',
      'alma de dragón en juego',
      'pelea a ciegas',
      'mapa sin visión',
    ],
    activityTags: ['match', 'scrim'],
    weight: 15,
    cooldownTurns: 12,
    actorCooldownTurns: 8,
    choices: [
      {
        id: 'commit_smite',
        label: 'Ir a robarlo',
        verb: 'timing',
        effect: { stats: { mechanics: 6, mentality: 3, reputation: 3 }, relations: { coach: 2 } },
        outcome: 'Fue al borde. El chat explotó.',
      },
      {
        id: 'bail_reset',
        label: 'Soltar y resetear',
        verb: 'choice',
        effect: { stats: { gameSense: 5, mentality: 1 }, relations: { coach: 4 } },
        outcome: 'Paciente. El mapa sigue vivo.',
      },
      {
        id: 'ask_peel',
        label: 'Pedir protección y golpe seguro',
        verb: 'talk',
        effect: { stats: { teamwork: 5, gameSense: 2 }, relations: { coach: 3, duo: 3 } },
        outcome: 'Teamplay limpio. Menos heroísmo.',
      },
    ],
  },
  {
    id: 'adc_peel_gap',
    family: 'roster',
    titleTemplate: 'Nadie te cubrió otra vez',
    bodyTemplate:
      'Tras una pelea fea en {{venue}}, {{actor}} mira la replay: {{cause}}. Otra vez: ¿mal posicionado o sin cobertura?',
    stages: ['academy', 'challengers', 'tier1'],
    roleTags: ['adc'],
    actors: ['duo', 'coach'],
    venues: ['home', 'academy', 'cafe'],
    causes: [
      'dive en bot sin aviso',
      'flank que nadie vio',
      'escape mal timed',
      'cero espacio para pegar',
    ],
    activityTags: ['scrim', 'match', 'vod'],
    weight: 14,
    cooldownTurns: 10,
    actorCooldownTurns: 6,
    threadKind: 'roster_rift',
    choices: [
      {
        id: 'own_pos',
        label: 'Bancarte tu posición',
        verb: 'talk',
        effect: { stats: { mentality: 3, mechanics: 3 }, relations: { duo: 4, coach: 2 } },
        outcome: 'Menos culpa. Más labs de spacing.',
      },
      {
        id: 'ask_peel_plan',
        label: 'Pedir un plan de cobertura',
        verb: 'sort',
        effect: { stats: { teamwork: 5, gameSense: 2 }, relations: { duo: 5, coach: 2 } },
        outcome: 'Acordaron coberturas. La línea respira.',
      },
      {
        id: 'tilt_chat',
        label: 'Explotar en voice',
        verb: 'talk',
        effect: { stats: { mentality: -5 }, relations: { duo: -6, coach: -3 } },
        outcome: 'Silencio tóxico. El roce crece.',
      },
    ],
  },
  {
    id: 'adc_duo_swap',
    family: 'roster',
    titleTemplate: 'Prueban otro dúo bot',
    bodyTemplate:
      '{{actor}} en {{venue}} suelta la bomba: prueban otra pareja bot “por unas series”. Motivo: {{cause}}.',
    stages: ['academy', 'challengers', 'tier1'],
    roleTags: ['adc', 'support'],
    actors: ['coach', 'manager'],
    venues: ['academy', 'cafe', 'arena'],
    causes: [
      'poca química',
      'composición nueva',
      'presión del board',
      'forma floja del support',
    ],
    activityTags: ['scrim', 'match'],
    weight: 12,
    cooldownTurns: 14,
    actorCooldownTurns: 10,
    threadKind: 'starting_spot',
    choices: [
      {
        id: 'accept_tryout',
        label: 'Aceptar la prueba',
        verb: 'talk',
        effect: { stats: { mentality: 2, reputation: 2 }, relations: { coach: 3, manager: 3, duo: -4 } },
        outcome: 'Profesionalismo. El duo lo siente.',
      },
      {
        id: 'defend_duo',
        label: 'Defender a tu duo',
        verb: 'talk',
        effect: { stats: { teamwork: 4, mentality: 2 }, relations: { duo: 6, coach: -2, manager: -1 } },
        outcome: 'Lealtad. El staff anota resistencia.',
      },
      {
        id: 'prove_scrims',
        label: 'Pedir 3 scrims de prueba',
        verb: 'timing',
        effect: { stats: { mechanics: 3, teamwork: 3 }, relations: { coach: 2, duo: 3 } },
        outcome: 'Compraste tiempo con resultados.',
      },
    ],
  },
  {
    id: 'sup_ward_budget',
    family: 'sponsor',
    titleTemplate: 'Visión o ítems ego',
    bodyTemplate:
      '{{actor}} te mira en {{venue}}: o comprás visión o farmeas daño “como carry”. Empuja {{cause}}.',
    stages: ['academy', 'challengers'],
    roleTags: ['support'],
    actors: ['coach', 'manager'],
    venues: ['home', 'academy', 'cafe'],
    causes: [
      'muertes sin mapa',
      'dragón sin visión',
      'oro tirado en ítems ego',
      'cero wards de control',
    ],
    activityTags: ['scrim', 'vod', 'match'],
    weight: 13,
    cooldownTurns: 10,
    actorCooldownTurns: 7,
    choices: [
      {
        id: 'ward_first',
        label: 'Visión primero, siempre',
        verb: 'choice',
        effect: { stats: { gameSense: 5, teamwork: 4 }, relations: { coach: 5, duo: 3 } },
        outcome: 'El mapa se ilumina. El ADC respira.',
      },
      {
        id: 'hybrid_build',
        label: 'Build a medias',
        verb: 'sort',
        effect: { stats: { gameSense: 3, mechanics: 2 }, relations: { coach: 2 } },
        outcome: 'Compromiso. Veremos en la serie.',
      },
      {
        id: 'ego_items',
        label: 'Ítems de impacto',
        verb: 'talk',
        effect: { stats: { mechanics: 3, mentality: -2 }, relations: { coach: -3, duo: -2 } },
        outcome: 'Más daño. Menos control. El staff duda.',
      },
    ],
  },
  {
    id: 'top_island_tilt',
    family: 'performance',
    titleTemplate: 'Solo en tu línea',
    bodyTemplate:
      'Nadie responde tus pings de ayuda. En {{venue}}, {{actor}} empuja {{cause}}. Estás solo arriba.',
    stages: ['soloq', 'academy', 'challengers'],
    roleTags: ['top'],
    actors: ['rival', 'duo'],
    venues: ['home', 'gym', 'cafe'],
    causes: [
      'matchup duro',
      'cero ayuda del equipo',
      'flame en el chat',
      'teletransporte fallido',
    ],
    activityTags: ['soloq', 'scrim', 'match'],
    weight: 13,
    cooldownTurns: 9,
    actorCooldownTurns: 6,
    threadKind: 'rivalry',
    choices: [
      {
        id: 'mute_focus',
        label: 'Mute y farmear enfocado',
        verb: 'choice',
        effect: { stats: { mentality: 5, mechanics: 3 }, relations: { rival: -2 } },
        outcome: 'Línea fría. Números limpios.',
      },
      {
        id: 'call_out',
        label: 'Pedir ayuda en voice',
        verb: 'talk',
        effect: { stats: { teamwork: 3, mentality: -1 }, relations: { duo: 2, coach: 1 } },
        outcome: 'Alguien escuchó. Tarde, pero escuchó.',
      },
      {
        id: 'allin_tp',
        label: 'Jugada ego con teletransporte',
        verb: 'timing',
        effect: { stats: { mechanics: 5, mentality: 2, reputation: 1 }, relations: { rival: 4 } },
        outcome: 'O highlight o int. La replay decide.',
      },
    ],
  },
];

export function archetypeById(id: string): SituationArchetype | undefined {
  return SITUATION_ARCHETYPES.find((a) => a.id === id);
}
