/**
 * Storylets parametrizados: arquetipos + familias del vertical slice.
 * Los eventos legacy del pack se adaptan en situationDirector.
 */
import type { SituationArchetype } from './types';

export const SITUATION_ARCHETYPES: SituationArchetype[] = [
  // —— Roster conflicts ——
  {
    id: 'roster_rift',
    family: 'roster',
    titleTemplate: 'Fisura en el roster',
    bodyTemplate:
      '{{actor}} te corta el paso en {{venue}}. La causa: {{cause}}. {{other}} mira desde atrás sin meterse… todavía.',
    stages: ['academy', 'challengers', 'tier1', 'worlds'],
    actors: ['coach', 'duo'],
    venues: ['academy', 'cafe', 'arena'],
    causes: ['derrota fea', 'tardanza al scrim', 'ego en voice', 'rotación de titular'],
    activityTags: ['scrim', 'match', 'vod'],
    weight: 11,
    cooldownTurns: 12,
    actorCooldownTurns: 8,
    threadKind: 'roster_rift',
    choices: [
      {
        id: 'mediate',
        label: 'Mediar en el medio',
        verb: 'talk',
        hint: 'Acercate y bajá la tensión',
        effect: { stats: { teamwork: 5, mentality: 2 }, relations: { coach: 3, duo: 3 } },
        outcome: 'Bajaste la temperatura. Quedó anotado.',
      },
      {
        id: 'back_actor',
        label: 'Respaldar a {{actor}}',
        verb: 'talk',
        effect: { stats: { teamwork: 2 } },
        actorRelations: { primary: 5, others: -4 },
        outcome: 'Tomaste partido. El otro no lo olvida.',
      },
      {
        id: 'confront',
        label: 'Confrontar de frente',
        verb: 'timing',
        hint: 'Timing de voz firme',
        effect: { stats: { mentality: 4, reputation: 2 }, relations: { coach: -2, duo: -2 } },
        outcome: 'Quedó claro quién manda el tono.',
      },
      {
        id: 'walk_away',
        label: 'Retirarte de la zona',
        verb: 'talk',
        effect: { stats: { mentality: -3 }, relations: { coach: -1, duo: -1 } },
        outcome: 'Te fuiste. El conflicto sigue vivo.',
      },
    ],
  },
  {
    id: 'sub_pressure',
    family: 'roster',
    titleTemplate: 'Amenaza de suplente',
    bodyTemplate:
      '{{actor}} te muestra el celular: el staff habla de rotar. Motivo: {{cause}}. Estás en {{venue}}.',
    stages: ['challengers', 'tier1', 'worlds'],
    actors: ['coach', 'manager'],
    venues: ['academy', 'arena', 'cafe'],
    causes: ['forma baja', 'fatiga visible', 'mala serie', 'presión del board'],
    requireRelations: { coach: 20 },
    weight: 9,
    cooldownTurns: 14,
    actorCooldownTurns: 10,
    threadKind: 'starting_spot',
    choices: [
      {
        id: 'prove',
        label: 'Pedir lab extra',
        verb: 'timing',
        effect: { stats: { mechanics: 5, mentality: 3 }, relations: { coach: 4 } },
        outcome: 'Compraste tiempo con sangre.',
      },
      {
        id: 'negotiate_role',
        label: 'Negociar el rol',
        verb: 'sort',
        hint: 'Ordená prioridades en el papel',
        effect: { stats: { teamwork: 4, money: -2 }, relations: { manager: 3, coach: 2 } },
        outcome: 'Reordenaste expectativas.',
      },
      {
        id: 'ignore_noise',
        label: 'Ignorar el ruido',
        verb: 'talk',
        effect: { stats: { mentality: -4, reputation: 2 }, relations: { coach: -3 } },
        outcome: 'El rumor crece sin respuesta.',
      },
    ],
  },
  {
    id: 'duo_trust_test',
    family: 'roster',
    titleTemplate: 'Test de confianza',
    bodyTemplate:
      '{{actor}} se cruzó de brazos. "{{cause}}". El lugar: {{venue}}. Quiere una respuesta, no un speech.',
    stages: ['soloq', 'academy', 'challengers', 'tier1'],
    actors: ['duo'],
    venues: ['home', 'cafe', 'academy'],
    causes: ['promesa rota de duo', 'clip incómodo', 'llamada en ranked', 'silencio post-derrota'],
    activityTags: ['soloq', 'content', 'rest'],
    weight: 10,
    cooldownTurns: 10,
    actorCooldownTurns: 7,
    threadKind: 'roster_rift',
    choices: [
      {
        id: 'apologize',
        label: 'Reconocer el error',
        verb: 'talk',
        effect: { stats: { mentality: 3, teamwork: 4 }, relations: { duo: 7 } },
        outcome: 'Se distiende. Anotan la página.',
      },
      {
        id: 'explain',
        label: 'Explicar el contexto',
        verb: 'sort',
        effect: { stats: { gameSense: 3 }, relations: { duo: 2 } },
        outcome: 'Entiende… a medias.',
      },
      {
        id: 'deflect',
        label: 'Cambiar de tema',
        verb: 'talk',
        effect: { stats: { mentality: -2 }, relations: { duo: -5 } },
        outcome: 'Queda un filo entre ustedes.',
      },
    ],
  },

  // —— Sponsor / contract ——
  {
    id: 'sponsor_offer',
    family: 'sponsor',
    titleTemplate: 'Oferta sobre la mesa',
    bodyTemplate:
      '{{actor}} abre una carpeta en {{venue}}. Cláusula clave: {{cause}}. Podés inspeccionar, negociar o firmar a ciegas.',
    stages: ['academy', 'challengers', 'tier1', 'worlds'],
    actors: ['manager'],
    venues: ['cafe', 'home', 'academy'],
    causes: ['exclusividad de stream', 'apariencia en redes', 'bonus por wins', 'penalidad por tilt público'],
    activityTags: ['content'],
    weight: 10,
    cooldownTurns: 12,
    actorCooldownTurns: 9,
    threadKind: 'sponsor',
    minigame: {
      kind: 'negotiation',
      title: 'Mesa de contrato',
      blurb: 'Leé la letra chica bajo presión.',
      difficulty: 2,
    },
    choices: [
      {
        id: 'inspect',
        label: 'Inspeccionar cláusulas',
        verb: 'sort',
        hint: 'Arrastrá y ordená los papeles',
        effect: { stats: { money: 3, reputation: 2 }, relations: { manager: 2 } },
        outcome: 'Encontraste una trampa. Mejor posición.',
      },
      {
        id: 'negotiate',
        label: 'Negociar el %',
        verb: 'timing',
        effect: { stats: { money: 6, reputation: 1 }, relations: { manager: 4 } },
        outcome: 'Sacaste un punto más. Firmás con sonrisa tensa.',
      },
      {
        id: 'sign_fast',
        label: 'Firmar ya',
        verb: 'talk',
        effect: { stats: { money: 8, mentality: -2 }, relations: { manager: 5, coach: -2 } },
        outcome: 'Plata rápida. El team mira de reojo.',
      },
      {
        id: 'walk_deal',
        label: 'Rechazar la mesa',
        verb: 'talk',
        effect: { stats: { reputation: 3, money: -1 }, relations: { manager: -4 } },
        outcome: 'Quedás limpio… y más pobre.',
      },
    ],
  },
  {
    id: 'contract_renewal',
    family: 'sponsor',
    titleTemplate: 'Renovación en juego',
    bodyTemplate:
      '{{actor}} pone el reloj sobre la mesa en {{venue}}. El board aprieta por {{cause}}.',
    stages: ['challengers', 'tier1', 'worlds'],
    actors: ['manager', 'coach'],
    venues: ['cafe', 'academy'],
    causes: ['números flojos', 'edad en el radar', 'otra oferta rival', 'cláusula de salida'],
    weight: 9,
    cooldownTurns: 16,
    actorCooldownTurns: 12,
    threadKind: 'contract',
    choices: [
      {
        id: 'ask_raise',
        label: 'Pedir suba',
        verb: 'timing',
        effect: { stats: { money: 7, mentality: 2 }, relations: { manager: -2, coach: 1 } },
        outcome: 'Forcejeaste el número.',
      },
      {
        id: 'security',
        label: 'Priorizar seguridad',
        verb: 'sort',
        effect: { stats: { money: 3, mentality: 5 }, relations: { manager: 4, coach: 3 } },
        outcome: 'Menos upside, más piso.',
      },
      {
        id: 'threaten_leave',
        label: 'Amenazar con irte',
        verb: 'talk',
        effect: { stats: { reputation: 4, teamwork: -4 }, relations: { manager: -5, coach: -3 } },
        outcome: 'Quedó el puente medio quemado.',
      },
    ],
  },

  // —— Performance / health ——
  {
    id: 'performance_dip',
    family: 'performance',
    titleTemplate: 'Señal roja',
    bodyTemplate:
      'En {{venue}} ves las señales: {{cause}}. {{actor}} ya lo notó. Hay que diagnosticar antes de que explote.',
    stages: ['soloq', 'academy', 'challengers', 'tier1', 'worlds'],
    actors: ['coach', 'duo', 'manager'],
    venues: ['home', 'gym', 'academy'],
    causes: ['muñeca cargada', 'sueño roto', 'tilt silencioso', 'setup fallando', 'ansiedad pre-serie'],
    activityTags: ['soloq', 'rest', 'match'],
    weight: 11,
    cooldownTurns: 11,
    actorCooldownTurns: 8,
    threadKind: 'burnout',
    choices: [
      {
        id: 'physio',
        label: 'Tratamiento / fisio',
        verb: 'timing',
        effect: { stats: { mentality: 5, mechanics: 2 }, relations: { coach: 2 } },
        outcome: 'Bajás carga. El cuerpo agradece.',
      },
      {
        id: 'train_through',
        label: 'Empujar el grind',
        verb: 'timing',
        effect: { stats: { mechanics: 6, mentality: -5 }, relations: { coach: 1, duo: -1 } },
        outcome: 'Rendís hoy; pagás mañana.',
      },
      {
        id: 'full_rest',
        label: 'Protocolo de descanso',
        verb: 'talk',
        effect: { stats: { mentality: 7, mechanics: -2 }, relations: { duo: 2 } },
        outcome: 'Apagás el PC. La forma espera.',
      },
      {
        id: 'fix_setup',
        label: 'Arreglar el setup',
        verb: 'sort',
        effect: { stats: { mechanics: 4, money: -3 }, relations: { manager: 1 } },
        outcome: 'Cableado limpio. Menos fricción.',
      },
    ],
  },
  {
    id: 'voice_chaos',
    family: 'roster',
    titleTemplate: 'Caos en voice',
    bodyTemplate:
      'En {{venue}}, {{actor}} corta a todos. Motivo: {{cause}}. {{other}} se queda callado un segundo de más.',
    stages: ['academy', 'challengers', 'tier1'],
    actors: ['coach', 'duo'],
    venues: ['academy', 'cafe'],
    causes: ['call contradictorio', 'ping spam', 'tilt post-fight', 'horario corrido'],
    activityTags: ['scrim', 'vod'],
    weight: 9,
    cooldownTurns: 11,
    actorCooldownTurns: 7,
    threadKind: 'roster_rift',
    choices: [
      {
        id: 'reset_comms',
        label: 'Resetear comms',
        verb: 'talk',
        effect: { stats: { teamwork: 6, mentality: 2 }, relations: { coach: 3, duo: 3 } },
        outcome: 'Volvieron a hablar en el mismo idioma.',
      },
      {
        id: 'side_actor',
        label: 'Bancarle el call a {{actor}}',
        verb: 'talk',
        actorRelations: { primary: 5, others: -3 },
        effect: { stats: { teamwork: 1 } },
        outcome: 'Quedó un bando. El otro lo marca.',
      },
      {
        id: 'mute_self',
        label: 'Mute propio y focus',
        verb: 'timing',
        effect: { stats: { mechanics: 4, teamwork: -3 }, relations: { coach: -2 } },
        outcome: 'Jugaste limpio, pero el team quedó frío.',
      },
    ],
  },
  {
    id: 'starting_spot_leak',
    family: 'roster',
    titleTemplate: 'Filtración de titular',
    bodyTemplate:
      '{{actor}} te muestra un pantallazo en {{venue}}: el board discute tu spot por {{cause}}.',
    stages: ['challengers', 'tier1', 'worlds'],
    actors: ['manager', 'coach'],
    venues: ['academy', 'arena', 'cafe'],
    causes: ['serie chata', 'contenido > lab', 'comparativa con academy', 'fatiga pública'],
    weight: 10,
    cooldownTurns: 16,
    actorCooldownTurns: 10,
    threadKind: 'starting_spot',
    choices: [
      {
        id: 'own_it',
        label: 'Pedir feedback duro',
        verb: 'talk',
        effect: { stats: { mentality: 3, gameSense: 4 }, relations: { coach: 4 } },
        outcome: 'Dolor útil. Quedó plan.',
      },
      {
        id: 'pr_spin',
        label: 'Armar narrativa con {{manager}}',
        verb: 'sort',
        effect: { stats: { reputation: 5, money: -2 }, relations: { manager: 4, coach: -1 } },
        outcome: 'El ruido se vuelve controlado.',
      },
      {
        id: 'shadow_queue',
        label: 'Grind secreto',
        verb: 'timing',
        effect: { stats: { mechanics: 6, mentality: -2 }, relations: { duo: 2 } },
        outcome: 'Subís nivel en silencio.',
      },
    ],
  },
  {
    id: 'brand_ambush',
    family: 'sponsor',
    titleTemplate: 'Emboscada de marca',
    bodyTemplate:
      '{{actor}} te espera en {{venue}} con un brief express: {{cause}}. Hay cámara cerca.',
    stages: ['academy', 'challengers', 'tier1', 'worlds'],
    actors: ['manager'],
    venues: ['cafe', 'arena', 'home'],
    causes: ['drop de merch', 'clip viral', 'rival con el mismo sponsor', 'deadline de campaña'],
    activityTags: ['content'],
    weight: 9,
    cooldownTurns: 12,
    actorCooldownTurns: 8,
    threadKind: 'sponsor',
    choices: [
      {
        id: 'take_brief',
        label: 'Aceptar el brief',
        verb: 'sort',
        effect: { stats: { reputation: 5, money: 6, mentality: -2 }, relations: { manager: 4 } },
        outcome: 'Plata rápida. Agenda más densa.',
      },
      {
        id: 'protect_focus',
        label: 'Proteger el focus competitivo',
        verb: 'talk',
        effect: { stats: { mentality: 3, reputation: -2 }, relations: { manager: -3, coach: 3 } },
        outcome: '{{coach}} asiente. {{manager}} anota la fricción.',
      },
      {
        id: 'renegotiate',
        label: 'Renegociar alcance',
        verb: 'timing',
        effect: { stats: { money: 3, reputation: 2 }, relations: { manager: 2 } },
        outcome: 'Quedó un alcance más sano.',
      },
    ],
  },
  {
    id: 'clause_trap',
    family: 'sponsor',
    titleTemplate: 'Cláusula escondida',
    bodyTemplate:
      'En {{venue}}, {{actor}} señala una línea del PDF: {{cause}}. {{other}} ya firmó algo parecido.',
    stages: ['challengers', 'tier1', 'worlds'],
    actors: ['manager', 'coach'],
    venues: ['cafe', 'academy'],
    causes: ['exclusividad de stream', 'penalidad por no clasificar', 'imagen con rival', 'NDA de draft'],
    weight: 8,
    cooldownTurns: 14,
    actorCooldownTurns: 9,
    threadKind: 'contract',
    choices: [
      {
        id: 'lawyer_up',
        label: 'Pedir revisión legal',
        verb: 'sort',
        effect: { stats: { money: -4, mentality: 2 }, relations: { manager: 1, coach: 2 } },
        outcome: 'Más lento, más seguro.',
      },
      {
        id: 'sign_anyway',
        label: 'Firmar y seguir',
        verb: 'talk',
        effect: { stats: { money: 8, reputation: 3 }, relations: { manager: 5 }, flags: { riskyClause: 1 } },
        outcome: 'Plata ahora. Riesgo después.',
      },
      {
        id: 'walk_paper',
        label: 'Levantarte de la mesa',
        verb: 'talk',
        effect: { stats: { reputation: 2, money: -2 }, relations: { manager: -4 } },
        outcome: 'Quedó claro tu límite.',
      },
    ],
  },
  {
    id: 'late_night_spiral',
    family: 'performance',
    titleTemplate: 'Espiral de madrugada',
    bodyTemplate:
      'Son las 3 en {{venue}}. {{actor}} te mira la cara: {{cause}}. El setup sigue prendido.',
    stages: ['soloq', 'academy', 'challengers', 'tier1'],
    actors: ['duo', 'coach'],
    venues: ['home', 'gym', 'cafe'],
    causes: ['LP tilt', 'insomnio', 'caffeine crash', 'doomscroll de reddit'],
    activityTags: ['soloq', 'rest'],
    weight: 10,
    cooldownTurns: 10,
    actorCooldownTurns: 6,
    threadKind: 'burnout',
    choices: [
      {
        id: 'force_sleep',
        label: 'Apagar todo',
        verb: 'talk',
        effect: { stats: { mentality: 6, mechanics: -2 }, relations: { duo: 3 } },
        outcome: 'Dormís. Mañana existe.',
      },
      {
        id: 'one_more',
        label: 'Una más',
        verb: 'timing',
        effect: { stats: { mechanics: 3, mentality: -5 }, relations: { coach: -2 } },
        outcome: 'Una más… y otra.',
      },
      {
        id: 'walk_block',
        label: 'Salir a caminar',
        verb: 'sort',
        effect: { stats: { mentality: 4, teamwork: 1 }, relations: { duo: 2 } },
        outcome: 'El aire corta el loop.',
      },
    ],
  },
  {
    id: 'form_check',
    family: 'performance',
    titleTemplate: 'Chequeo de forma',
    bodyTemplate:
      '{{actor}} te para en {{venue}}. Ve un problema concreto: {{cause}}. ¿Cómo lo encarás?',
    stages: ['academy', 'challengers', 'tier1', 'worlds'],
    actors: ['coach', 'manager'],
    venues: ['academy', 'arena'],
    causes: ['farm flojo', 'muertes tempranas', 'poca presencia en mapa', 'composiciones predecibles'],
    activityTags: ['vod', 'scrim', 'match'],
    weight: 9,
    cooldownTurns: 11,
    actorCooldownTurns: 7,
    choices: [
      {
        id: 'accept_plan',
        label: 'Aceptar plan de lab',
        verb: 'sort',
        effect: { stats: { gameSense: 5, mentality: 2 }, relations: { coach: 5 } },
        outcome: 'Plan concreto. Menos ego.',
      },
      {
        id: 'argue_sample',
        label: 'Discutir la muestra',
        verb: 'talk',
        effect: { stats: { mentality: -2, reputation: 1 }, relations: { coach: -3 } },
        outcome: 'Defendiste el sample. Quedó roce.',
      },
      {
        id: 'prove_queue',
        label: 'Probarlo en cola',
        verb: 'timing',
        effect: { stats: { mechanics: 5, mentality: 1 }, relations: { coach: 2, duo: 2 } },
        outcome: 'Los números hablan después.',
      },
    ],
  },
  {
    id: 'rival_probe',
    family: 'performance',
    titleTemplate: 'El rival te mide',
    bodyTemplate:
      '{{actor}} aparece en {{venue}} con una sonrisa de scout. Empuja el tema: {{cause}}.',
    stages: ['soloq', 'academy', 'challengers', 'tier1', 'worlds'],
    actors: ['rival'],
    venues: ['cafe', 'arena', 'gym'],
    causes: [
      'tu último highlight',
      'rumor de suplente',
      'comparación de puntuación',
      'plan de equipo filtrado',
    ],
    weight: 8,
    cooldownTurns: 10,
    actorCooldownTurns: 6,
    threadKind: 'rivalry',
    choices: [
      {
        id: 'banter',
        label: 'Banter limpio',
        verb: 'talk',
        effect: { stats: { reputation: 3, mentality: 2 }, relations: { rival: 4 } },
        outcome: 'Queda respeto. Y material de clip.',
      },
      {
        id: 'ice',
        label: 'Cortar en seco',
        verb: 'talk',
        effect: { stats: { mentality: 1 }, relations: { rival: -3 } },
        outcome: 'Silencio incómodo. Victoria chica.',
      },
      {
        id: 'challenge',
        label: 'Desafiar a customs',
        verb: 'timing',
        effect: { stats: { mechanics: 4, reputation: 2 }, relations: { rival: 6 } },
        outcome: 'Quedó pactado. El timeline vibra.',
      },
    ],
  },
  {
    id: 'rival_customs',
    family: 'performance',
    titleTemplate: 'Customs bajo fuego',
    bodyTemplate:
      '{{actor}} te espera en {{venue}}. Ya no es chiste: quiere customs por {{cause}}. La rivalidad escala.',
    stages: ['academy', 'challengers', 'tier1', 'worlds'],
    actors: ['rival'],
    venues: ['cafe', 'arena', 'gym'],
    causes: ['tu última serie', 'un clip viral', 'un scout en voice', 'el draft filtrado'],
    weight: 11,
    cooldownTurns: 9,
    actorCooldownTurns: 5,
    threadKind: 'rivalry',
    choices: [
      {
        id: 'accept_customs',
        label: 'Aceptar customs',
        verb: 'timing',
        effect: { stats: { mechanics: 5, mentality: 1, reputation: 2 }, relations: { rival: 5 } },
        outcome: 'Customs densos. El hilo de rivalidad arde.',
      },
      {
        id: 'public_refuse',
        label: 'Rechazar en público',
        verb: 'talk',
        effect: { stats: { mentality: 2, reputation: -1 }, relations: { rival: -4 } },
        outcome: 'Quedó frío. El circuit habla igual.',
      },
      {
        id: 'coach_mediate',
        label: 'Meter al coach de mediador',
        verb: 'sort',
        effect: { stats: { teamwork: 3 }, relations: { rival: 2, coach: 3 } },
        outcome: 'Marek baja la temperatura. Un poco.',
      },
    ],
  },
  {
    id: 'rival_showdown',
    family: 'performance',
    titleTemplate: 'Cara a cara',
    bodyTemplate:
      '{{actor}} te corta el paso en {{venue}}. Trash talk por {{cause}}. Esto ya es personal.',
    stages: ['challengers', 'tier1', 'worlds'],
    actors: ['rival'],
    venues: ['arena', 'cafe'],
    causes: ['la serie de esta semana', 'un leak de starting', 'tu maestría', 'el público'],
    weight: 13,
    cooldownTurns: 8,
    actorCooldownTurns: 4,
    threadKind: 'rivalry',
    choices: [
      {
        id: 'stare_down',
        label: 'Aguantar la mirada',
        verb: 'timing',
        effect: { stats: { mentality: 4, reputation: 3 }, relations: { rival: 3 } },
        outcome: 'No parpadeás. El hilo queda al rojo.',
      },
      {
        id: 'clap_back',
        label: 'Responder al trash',
        verb: 'timing',
        effect: { stats: { reputation: 4, mentality: -1 }, relations: { rival: 6 } },
        outcome: 'Clip. Guerra declarada. Arena en llamas.',
      },
      {
        id: 'walk_away',
        label: 'Darle la espalda',
        verb: 'talk',
        effect: { stats: { mentality: 2 }, relations: { rival: -5, coach: 2 } },
        outcome: 'Te vas. Marek asiente. El rival odia el silencio.',
      },
    ],
  },

  // —— Identidad de rol (solo dispara si jugás ese carril) ——
  {
    id: 'mid_roam_blame',
    family: 'roster',
    titleTemplate: 'Saliste de mid y te culpan',
    bodyTemplate:
      '{{actor}} te corta en {{venue}}: te fuiste a ayudar y dejaste tu línea sola. Motivo: {{cause}}. {{other}} no dice nada, pero se nota.',
    stages: ['academy', 'challengers', 'tier1'],
    roleTags: ['mid'],
    actors: ['coach', 'duo'],
    venues: ['home', 'academy', 'cafe'],
    causes: [
      'ayuda que no cerró',
      'perdiste presión en mid',
      'el rival llegó con teletransporte',
      'oleada que se te vino encima',
    ],
    activityTags: ['soloq', 'scrim', 'match'],
    weight: 14,
    cooldownTurns: 10,
    actorCooldownTurns: 7,
    threadKind: 'roster_rift',
    choices: [
      {
        id: 'own_it',
        label: 'Bancarte el error',
        verb: 'talk',
        effect: { stats: { mentality: 3, gameSense: 3 }, relations: { coach: 4, duo: 2 } },
        outcome: 'Responsabilidad. La review duele menos.',
      },
      {
        id: 'explain_tempo',
        label: 'Explicar por qué saliste',
        verb: 'talk',
        effect: { stats: { gameSense: 5 }, relations: { coach: -1, duo: 1 } },
        outcome: 'Defendiste la lectura. Quedó roce.',
      },
      {
        id: 'lab_roams',
        label: 'Practicar salidas en customs',
        verb: 'timing',
        effect: { stats: { mechanics: 4, gameSense: 2 }, relations: { coach: 3 } },
        outcome: 'Compraste perdón con reps.',
      },
    ],
  },
  {
    id: 'mid_prio_vs_side',
    family: 'performance',
    titleTemplate: '¿Presionar mid o ir a ayudar?',
    bodyTemplate:
      'Decisión rápida en {{venue}}: ¿seguís empujando mid o rotás a otra línea? {{actor}} empuja {{cause}}. Si fallás el call, se nota en el marcador.',
    stages: ['challengers', 'tier1', 'worlds'],
    roleTags: ['mid'],
    actors: ['coach', 'duo'],
    venues: ['academy', 'arena'],
    causes: [
      'objetivo chico por pelear',
      'estado de la oleada',
      'poca visión en el río',
      'teletransporte rival listo',
    ],
    activityTags: ['scrim', 'match', 'vod'],
    weight: 13,
    cooldownTurns: 11,
    actorCooldownTurns: 7,
    choices: [
      {
        id: 'hold_prio',
        label: 'Seguir presionando mid',
        verb: 'choice',
        effect: { stats: { gameSense: 4, mechanics: 2 }, relations: { coach: 2 } },
        outcome: 'Controlaste la oleada. El mapa respiró.',
      },
      {
        id: 'rotate_side',
        label: 'Ir a ayudar la otra línea',
        verb: 'timing',
        effect: { stats: { teamwork: 5, gameSense: 2 }, relations: { duo: 4, coach: 1 } },
        outcome: 'Llegaste a tiempo. El lado agradece.',
      },
      {
        id: 'defer_call',
        label: 'Dejar la decisión al coach',
        verb: 'talk',
        effect: { stats: { mentality: -2 }, relations: { coach: 3 } },
        outcome: 'Menos ego. Menos ownership.',
      },
    ],
  },
  {
    id: 'jgl_path_leak',
    family: 'performance',
    titleTemplate: 'Te leyeron la ruta',
    bodyTemplate:
      '{{actor}} marca tu recorrido en {{venue}}. Empuja {{cause}}. En voice piden cambiar el plan… o invadir igual.',
    stages: ['academy', 'challengers', 'tier1', 'worlds'],
    roleTags: ['jungle'],
    actors: ['coach', 'rival'],
    venues: ['home', 'academy', 'arena'],
    causes: [
      'visión enemiga profunda',
      'clip del rival',
      'patrón demasiado predecible',
      'te trackean los campamentos',
    ],
    activityTags: ['vod', 'scrim', 'match'],
    weight: 14,
    cooldownTurns: 10,
    actorCooldownTurns: 6,
    threadKind: 'rivalry',
    choices: [
      {
        id: 'change_path',
        label: 'Cambiar la ruta ya',
        verb: 'sort',
        effect: { stats: { gameSense: 6 }, relations: { coach: 4 } },
        outcome: 'Nuevo recorrido. El rival pierde el rastro.',
      },
      {
        id: 'invade_anyway',
        label: 'Invadir igual',
        verb: 'timing',
        effect: { stats: { mechanics: 4, mentality: 2 }, relations: { rival: 3, coach: -2 } },
        outcome: 'Jugada de ego. Si sale, highlight; si no, review.',
      },
      {
        id: 'ward_lab',
        label: 'Lab de visión primero',
        verb: 'talk',
        effect: { stats: { gameSense: 4, teamwork: 2 }, relations: { coach: 3, duo: 2 } },
        outcome: 'Visión primero. Ruta después.',
      },
    ],
  },
  {
    id: 'jgl_steal_call',
    family: 'performance',
    titleTemplate: '¿Robar el objetivo o soltar?',
    bodyTemplate:
      'Objetivo grande en {{venue}}. {{actor}} grita el call: {{cause}}. El golpe final está en tus manos.',
    stages: ['tier1', 'worlds'],
    roleTags: ['jungle'],
    actors: ['coach'],
    venues: ['arena', 'academy'],
    causes: [
      'setup de Baron',
      'alma de dragón en juego',
      'pelea a ciegas',
      'mapa sin visión',
    ],
    activityTags: ['match', 'scrim'],
    weight: 15,
    cooldownTurns: 12,
    actorCooldownTurns: 8,
    choices: [
      {
        id: 'commit_smite',
        label: 'Ir a robarlo',
        verb: 'timing',
        effect: { stats: { mechanics: 6, mentality: 3, reputation: 3 }, relations: { coach: 2 } },
        outcome: 'Fue al borde. El chat explotó.',
      },
      {
        id: 'bail_reset',
        label: 'Soltar y resetear',
        verb: 'choice',
        effect: { stats: { gameSense: 5, mentality: 1 }, relations: { coach: 4 } },
        outcome: 'Paciente. El mapa sigue vivo.',
      },
      {
        id: 'ask_peel',
        label: 'Pedir protección y golpe seguro',
        verb: 'talk',
        effect: { stats: { teamwork: 5, gameSense: 2 }, relations: { coach: 3, duo: 3 } },
        outcome: 'Teamplay limpio. Menos heroísmo.',
      },
    ],
  },
  {
    id: 'adc_peel_gap',
    family: 'roster',
    titleTemplate: 'Nadie te cubrió otra vez',
    bodyTemplate:
      'Tras una pelea fea en {{venue}}, {{actor}} mira la replay: {{cause}}. Otra vez: ¿mal posicionado o sin cobertura?',
    stages: ['academy', 'challengers', 'tier1'],
    roleTags: ['adc'],
    actors: ['duo', 'coach'],
    venues: ['home', 'academy', 'cafe'],
    causes: [
      'dive en bot sin aviso',
      'flank que nadie vio',
      'escape mal timed',
      'cero espacio para pegar',
    ],
    activityTags: ['scrim', 'match', 'vod'],
    weight: 14,
    cooldownTurns: 10,
    actorCooldownTurns: 6,
    threadKind: 'roster_rift',
    choices: [
      {
        id: 'own_pos',
        label: 'Bancarte tu posición',
        verb: 'talk',
        effect: { stats: { mentality: 3, mechanics: 3 }, relations: { duo: 4, coach: 2 } },
        outcome: 'Menos culpa. Más labs de spacing.',
      },
      {
        id: 'ask_peel_plan',
        label: 'Pedir un plan de cobertura',
        verb: 'sort',
        effect: { stats: { teamwork: 5, gameSense: 2 }, relations: { duo: 5, coach: 2 } },
        outcome: 'Acordaron coberturas. La línea respira.',
      },
      {
        id: 'tilt_chat',
        label: 'Explotar en voice',
        verb: 'talk',
        effect: { stats: { mentality: -5 }, relations: { duo: -6, coach: -3 } },
        outcome: 'Silencio tóxico. El roce crece.',
      },
    ],
  },
  {
    id: 'adc_duo_swap',
    family: 'roster',
    titleTemplate: 'Prueban otro dúo bot',
    bodyTemplate:
      '{{actor}} en {{venue}} suelta la bomba: prueban otra pareja bot “por unas series”. Motivo: {{cause}}.',
    stages: ['academy', 'challengers', 'tier1'],
    roleTags: ['adc', 'support'],
    actors: ['coach', 'manager'],
    venues: ['academy', 'cafe', 'arena'],
    causes: [
      'poca química',
      'composición nueva',
      'presión del board',
      'forma floja del support',
    ],
    activityTags: ['scrim', 'match'],
    weight: 12,
    cooldownTurns: 14,
    actorCooldownTurns: 10,
    threadKind: 'starting_spot',
    choices: [
      {
        id: 'accept_tryout',
        label: 'Aceptar la prueba',
        verb: 'talk',
        effect: { stats: { mentality: 2, reputation: 2 }, relations: { coach: 3, manager: 3, duo: -4 } },
        outcome: 'Profesionalismo. El duo lo siente.',
      },
      {
        id: 'defend_duo',
        label: 'Defender a tu duo',
        verb: 'talk',
        effect: { stats: { teamwork: 4, mentality: 2 }, relations: { duo: 6, coach: -2, manager: -1 } },
        outcome: 'Lealtad. El staff anota resistencia.',
      },
      {
        id: 'prove_scrims',
        label: 'Pedir 3 scrims de prueba',
        verb: 'timing',
        effect: { stats: { mechanics: 3, teamwork: 3 }, relations: { coach: 2, duo: 3 } },
        outcome: 'Compraste tiempo con resultados.',
      },
    ],
  },
  {
    id: 'sup_ward_budget',
    family: 'sponsor',
    titleTemplate: 'Visión o ítems ego',
    bodyTemplate:
      '{{actor}} te mira en {{venue}}: o comprás visión o farmeas daño “como carry”. Empuja {{cause}}.',
    stages: ['academy', 'challengers'],
    roleTags: ['support'],
    actors: ['coach', 'manager'],
    venues: ['home', 'academy', 'cafe'],
    causes: [
      'muertes sin mapa',
      'dragón sin visión',
      'oro tirado en ítems ego',
      'cero wards de control',
    ],
    activityTags: ['scrim', 'vod', 'match'],
    weight: 13,
    cooldownTurns: 10,
    actorCooldownTurns: 7,
    choices: [
      {
        id: 'ward_first',
        label: 'Visión primero, siempre',
        verb: 'choice',
        effect: { stats: { gameSense: 5, teamwork: 4 }, relations: { coach: 5, duo: 3 } },
        outcome: 'El mapa se ilumina. El ADC respira.',
      },
      {
        id: 'hybrid_build',
        label: 'Build a medias',
        verb: 'sort',
        effect: { stats: { gameSense: 3, mechanics: 2 }, relations: { coach: 2 } },
        outcome: 'Compromiso. Veremos en la serie.',
      },
      {
        id: 'ego_items',
        label: 'Ítems de impacto',
        verb: 'talk',
        effect: { stats: { mechanics: 3, mentality: -2 }, relations: { coach: -3, duo: -2 } },
        outcome: 'Más daño. Menos control. El staff duda.',
      },
    ],
  },
  {
    id: 'top_island_tilt',
    family: 'performance',
    titleTemplate: 'Solo en tu línea',
    bodyTemplate:
      'Nadie responde tus pings de ayuda. En {{venue}}, {{actor}} empuja {{cause}}. Estás solo arriba.',
    stages: ['soloq', 'academy', 'challengers'],
    roleTags: ['top'],
    actors: ['rival', 'duo'],
    venues: ['home', 'gym', 'cafe'],
    causes: [
      'matchup duro',
      'cero ayuda del equipo',
      'flame en el chat',
      'teletransporte fallido',
    ],
    activityTags: ['soloq', 'scrim', 'match'],
    weight: 13,
    cooldownTurns: 9,
    actorCooldownTurns: 6,
    threadKind: 'rivalry',
    choices: [
      {
        id: 'mute_focus',
        label: 'Mute y farmear enfocado',
        verb: 'choice',
        effect: { stats: { mentality: 5, mechanics: 3 }, relations: { rival: -2 } },
        outcome: 'Línea fría. Números limpios.',
      },
      {
        id: 'call_out',
        label: 'Pedir ayuda en voice',
        verb: 'talk',
        effect: { stats: { teamwork: 3, mentality: -1 }, relations: { duo: 2, coach: 1 } },
        outcome: 'Alguien escuchó. Tarde, pero escuchó.',
      },
      {
        id: 'allin_tp',
        label: 'Jugada ego con teletransporte',
        verb: 'timing',
        effect: { stats: { mechanics: 5, mentality: 2, reputation: 1 }, relations: { rival: 4 } },
        outcome: 'O highlight o int. La replay decide.',
      },
    ],
  },
];

export function archetypeById(id: string): SituationArchetype | undefined {
  return SITUATION_ARCHETYPES.find((a) => a.id === id);
}
